/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete: operations["AuthController_signOut"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_listPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_view"];
        put?: never;
        post?: never;
        delete: operations["SessionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/laps/{lapNumber}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_lapSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["SessionsController_setVisibility"];
        trace?: never;
    };
    "/sessions/{sessionId}/share-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_share"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/share-links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SessionsController_revokeShareLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pilots/{pilotId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PilotsController_listByOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example piloto@exemplo.com */
            email: string;
            password: string;
            displayName: string;
        };
        /**
         * @description Visibilidade aplicada às sessões novas. Nasce `private`.
         * @enum {string}
         */
        Visibility: "private" | "unlisted" | "public";
        PilotDto: {
            id: string;
            displayName: string;
            /** @description Visibilidade aplicada às sessões novas. Nasce `private`. */
            defaultVisibility: components["schemas"]["Visibility"];
        };
        SignInDto: {
            /** @example piloto@exemplo.com */
            email: string;
            password: string;
        };
        ConditionsDto: {
            airTempCelsius: number | null;
            trackTempCelsius: number | null;
            relativeHumidityPct: number | null;
            windSpeedMs: number | null;
            skies: string | null;
            /** @description Segundos desde a meia-noite. */
            timeOfDaySeconds: number | null;
            trackUsage: string | null;
        };
        /**
         * @description Por que a volta não serve de referência. Vazio = serve.
         * @enum {string}
         */
        LapFlag: "incomplete" | "pit" | "off-track" | "slowdown";
        /**
         * @description Contínuo se liga com reta; discreto (marcha, booleano) se desenha em degrau.
         * @enum {string}
         */
        ChannelType: "number" | "integer" | "boolean" | "text" | "bitfield";
        /** @enum {string} */
        SeriesAxis: "time" | "lapDistPct";
        SeriesDto: {
            channel: string;
            unit: string;
            /** @description Contínuo se liga com reta; discreto (marcha, booleano) se desenha em degrau. */
            type: components["schemas"]["ChannelType"];
            axis: components["schemas"]["SeriesAxis"];
            x: number[];
            y: number[];
        };
        PublishedLapDto: {
            number: number;
            startSample: number;
            endSample: number;
            lapTimeSeconds: number | null;
            isComplete: boolean;
            /** @description Por que a volta não serve de referência. Vazio = serve. */
            flags: components["schemas"]["LapFlag"][];
            /** @description Séries por distância, como o desktop gravou. */
            series: components["schemas"]["SeriesDto"][];
        };
        PublishSessionDto: {
            /** @description O id que a sessão tem no desktop. Publicar de novo substitui. */
            id: string;
            trackId: string;
            trackName: string;
            trackConfig: string | null;
            trackLengthMeters: number | null;
            carId: string;
            carName: string;
            driverName: string | null;
            sessionType: string | null;
            /** Format: date-time */
            recordedAt: string | null;
            tickRate: number;
            sampleCount: number;
            conditions: components["schemas"]["ConditionsDto"];
            /** @description Melhor volta válida, calculada no desktop (ADR 0018). */
            bestLapTimeSeconds: number | null;
            laps: components["schemas"]["PublishedLapDto"][];
        };
        PublishedSessionSummaryDto: {
            sessionId: string;
            ownerId: string;
            ownerName: string;
            trackId: string;
            trackName: string;
            carId: string;
            carName: string;
            visibility: components["schemas"]["Visibility"];
            bestLapTimeSeconds: number | null;
            lapCount: number;
            /** Format: date-time */
            recordedAt: string | null;
            /** Format: date-time */
            publishedAt: string;
        };
        LapDto: {
            number: number;
            startSample: number;
            endSample: number;
            lapTimeSeconds: number | null;
            isComplete: boolean;
            /** @description Por que a volta não serve de referência. Vazio = serve. */
            flags: components["schemas"]["LapFlag"][];
        };
        PublishedSessionDto: {
            sessionId: string;
            ownerId: string;
            ownerName: string;
            trackId: string;
            trackName: string;
            carId: string;
            carName: string;
            visibility: components["schemas"]["Visibility"];
            bestLapTimeSeconds: number | null;
            lapCount: number;
            /** Format: date-time */
            recordedAt: string | null;
            /** Format: date-time */
            publishedAt: string;
            trackConfig: string | null;
            trackLengthMeters: number | null;
            driverName: string | null;
            sessionType: string | null;
            tickRate: number;
            conditions: components["schemas"]["ConditionsDto"];
            /** @description Voltas sem as séries; peça a série por volta. */
            laps: components["schemas"]["LapDto"][];
        };
        SetVisibilityDto: {
            visibility: components["schemas"]["Visibility"];
        };
        ShareLinkDto: {
            token: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Conta criada e sessão aberta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotDto"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            /** @description Sessão aberta; o cookie vem no `Set-Cookie`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotDto"];
                };
            };
            /** @description E-mail ou senha inválidos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotDto"];
                };
            };
            /** @description Sem login. O app funciona igual, só sem a nuvem. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSessionDto"];
            };
        };
        responses: {
            /** @description Sessão guardada. Publicar de novo substitui. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_listPublic: {
        parameters: {
            query?: {
                trackId?: string;
                carId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSessionSummaryDto"][];
                };
            };
        };
    };
    SessionsController_view: {
        parameters: {
            query?: {
                /** @description Token de um link de compartilhamento. */
                shareToken?: string;
            };
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSessionDto"];
                };
            };
            /** @description Não existe, ou este visitante não pode ver. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apagada. O que o piloto apagou no desktop some aqui. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_lapSeries: {
        parameters: {
            query?: {
                /** @description Token de um link de compartilhamento. */
                shareToken?: string;
            };
            header?: never;
            path: {
                sessionId: string;
                lapNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDto"][];
                };
            };
            /** @description Não existe, ou este visitante não pode ver. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_setVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetVisibilityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetVisibilityDto"];
                };
            };
        };
    };
    SessionsController_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkDto"];
                };
            };
        };
    };
    SessionsController_revokeShareLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PilotsController_listByOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pilotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSessionSummaryDto"][];
                };
            };
        };
    };
}
